#!/bin/bash

echo "Creating SBOM"
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp anchore/syft packages nginx:1.23.1 -o spdx-json=sbom-spdx.json

# if arg supplied is "--force" then dont scan for CVEs
if [[ "$*" != *"--force"* ]]; then
  echo -e "\nScaning image"
  docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock test-scan:1.0 scan-image nginx:1.23.1
fi

if [[ $? -eq 1 ]]; then
  echo "Found CRITICAL CVEs. Stopping Deploy"
  exit
fi

# deploy NGINX resources
kubectl apply -f resources

if [[ "$*" == *"--show-sbom"* ]]; then
  if [[ -f /tmp/sbom-spdx.json ]]; then
   echo -e /nShowing SBOM
   cat /tmp/sbom-spdx.json | jq
  fi
fi

echo "Waiting for deployment to complete"
kubectl rollout status deployment nginx

if [[ "$*" == *"--show-all"* ]]; then
  kubectl get all
fi

echo -e "\nDeployment complete"
