---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: nginx
        image: nginx:1.23.1
        ports:
        - containerPort: 8080
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
          seLinuxOptions:
            level: "s0:c123,c456"
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: nginx
              key: API_KEY
