---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  namespace: devops
automountServiceAccountToken: false

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: devops
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: devops
subjects:
- kind: ServiceAccount
  name: nginx
  namespace: devops
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

